/*
const { OrderModel } = require(path.resolve('./modules/orders/server/models/orders.server.model.js'));
*/

'use strict';

const path = require('path');
const _ = require('lodash');
const mongoose = require('mongoose');
const config = require(path.resolve('./config/config'));
const Schema = mongoose.Schema;

const OrderSchema = new Schema({
  id: { type: Number, unique: true },
  shop: { type: String, required: true },
  orgid: { type: String, required: true },
  is_deleted: { type: Boolean, default: false },
  deleted_at: { type: Date, default: null },
  created_at: { type: Date, default: null },
  updated_at: { type: Date, default: null },
  billing_address: {
    address1: { type: String, default: null },
    address2: { type: String, default: null },
    city: { type: String, default: null },
    company: { type: String, default: null },
    country: { type: String, default: null },
    first_name: { type: String, default: null },
    id: { type: String, default: 0 },
    last_name: { type: String, default: null },
    phone: { type: String, default: null },
    province: { type: String, default: null },
    zip: { type: String, default: null },
    name: { type: String, default: null },
    province_code: { type: String, default: null },
    country_code: { type: String, default: null },
    default: { type: Boolean, default: false },
    district: { type: String, default: null },
    district_code: { type: String, default: null },
    ward: { type: String, default: null },
    ward_code: { type: String, default: null }
  },
  browser_ip: { type: String, default: null },
  buyer_accepts_marketing: { type: Boolean, default: false },
  cancel_reason: { type: String, default: null },
  cancel_reason_extend: { type: String, default: null },
  cancelled_at: { type: Date, default: null },
  cart_token: { type: String, default: null },
  checkout_token: { type: String, default: null },
  client_details: {
    accept_language: { type: String, default: null },
    browser_ip: { type: String, default: null },
    session_hash: { type: String, default: null },
    user_agent: { type: String, default: null },
    browser_height: { type: String, default: null },
    browser_width: { type: String, default: null }
  },
  closed_at: { type: Date, default: null },
  currency: { type: String, default: null },
  customer: {
    accepts_marketing: { type: Boolean, default: false },
    addresses: [],
    created_at: { type: Date, default: null },
    default_address: Schema.Types.Mixed,
    email: { type: String, default: null },
    first_name: { type: String, default: null },
    id: { type: String, default: null },
    multipass_identifier: { type: String, default: null },
    last_name: { type: String, default: null },
    last_order_id: { type: String, default: null },
    last_order_name: { type: String, default: null },
    note: { type: String, default: null },
    orders_count: { type: Number, default: 0 },
    state: { type: String, default: null },
    tags: { type: String, default: null },
    tags_array: [],
    total_spent: { type: Number, default: 0 },
    updated_at: { type: Date, default: null },
    verified_email: { type: Boolean, default: false },
    send_email_invite: { type: Boolean, default: false },
    send_email_welcome: { type: Boolean, default: false },
    password: { type: String, default: null },
    password_confirmation: { type: String, default: null },
    group_name: { type: String, default: null },
    birthday: { type: Date, default: null },
    gender: { type: String, default: null },
    total_paid: { type: Number, default: 0 },
    phone: { type: String, default: null },
  },
  discount_codes: [],
  email: { type: String, default: null },
  financial_status: { type: String, default: null },
  fulfillments: [],
  fulfillment_status: { type: String, default: null },
  tags: { type: String, default: null },
  tags_array: [],
  gateway: { type: String, default: null },
  gateway_code: { type: String, lowercase: true, trim: true, default: null },
  landing_site: { type: String, default: null },
  landing_site_ref: { type: String, default: null },
  source: { type: String, default: null },
  line_items: [],
  name: { type: String, default: null },
  note: { type: String, default: null },
  number: { type: String, default: 0 },
  order_number: { type: String, default: null },
  processing_method: { type: String, default: null },
  referring_site: { type: String, default: null },
  refunds: [],
  shipping_address: {
    address1: { type: String, default: null },
    address2: { type: String, default: null },
    city: { type: String, default: null },
    company: { type: String, default: null },
    country: { type: String, default: null },
    first_name: { type: String, default: null },
    last_name: { type: String, default: null },
    latitude: { type: Number, default: 0 },
    longitude: { type: Number, default: 0 },
    phone: { type: String, default: null },
    province: { type: String, default: null },
    zip: { type: String, default: null },
    name: { type: String, default: null },
    province_code: { type: String, default: null },
    country_code: { type: String, default: null },
    district_code: { type: String, default: null },
    district: { type: String, default: null },
    ward: { type: String, default: null },
    ward_code: { type: String, default: null }
  },
  shipping_lines: [],
  source_name: { type: String, default: null },
  subtotal_price: { type: Number, default: 0 },
  tax_lines: { type: String, default: null },
  taxes_included: { type: Boolean, default: false },
  token: { type: String, default: null },
  total_discounts: { type: Number, default: 0 },
  total_line_items_price: { type: Number, default: 0 },
  total_price: { type: Number, default: 0 },
  total_tax: { type: Number, default: 0 },
  total_weight: { type: Number, default: 0 },
  transactions: [],
  note_attributes: [],
  confirmed_at: { type: Date, default: null },
  send_webhooks: { type: Boolean, default: false },
  send_receipt: { type: Boolean, default: false },
  send_fulfillment_receipt: { type: Boolean, default: false },
  inventory_behaviour: { type: String, default: null },
  closed_status: { type: String, default: null },
  cancelled_status: { type: String, default: null },
  confirmed_status: { type: String, default: null },
  user_id: { type: Number, default: null },
  device_id: { type: Number, default: 0 },
  has_promotion: { type: Boolean, default: false },
  is_cod_gateway: { type: Boolean, default: false },
  utm_source: { type: String, default: null },
  utm_medium: { type: String, default: null },
  utm_campaign: { type: String, default: null },
  utm_term: { type: String, default: null },
  utm_content: { type: String, default: null },
  paid_date: { type: Date, default: null },
  fulfillment_date: { type: Date, default: null },
  has_order_date: { type: Boolean, default: false },
  has_paid_date: { type: Boolean, default: false },
  has_fulfillment_date: { type: Boolean, default: false },
  is_deleted: { type: Boolean, default: false },
  session_sync_id: { type: String, default: null }
}, { versionKey: false });

OrderSchema.index({ orgid: 1, id: 1, updated_at: -1 });

const OrderModel = mongoose.model(config.dbprefix + '_Order', OrderSchema);

module.exports = { OrderModel };
